Monster death animation
CIA-hideout/three-chances pull request #28
Opened 2016-12-02 15:05 UTC by ivantjh

Damage calculation to be done in `gameControl.h`

2016-12-02 16:57 UTC, chesterhow requested changes

2016-12-02 16:57 UTC, chesterhow commented on src/constants.h
> +//const UINT GAME_HEIGHT = (TILE_SIZE * (VIEW_RANGE + 3)) * SCALE; // HUD will be 5 tile size
✂️

2016-12-02 16:57 UTC, chesterhow commented on src/constants.h
> + const int PLAYER_ATTACK_END_FRAME = 3;
Why is there `PLAYER_ATK_START_FRAME` as well as `PLAYER_ATTACK_START_FRAME`

2016-12-02 16:57 UTC, chesterhow commented on src/constants.h
> + const int PLAYER_ATTACK_END_FRAME = 3;
Hint: i'll stick with `ATK`

2016-12-02 16:57 UTC, chesterhow commented on src/entity.cpp
>  int currentId = 0;
Probably missed this from last time but when did this get here and why isnt it a proper private variable

2016-12-02 16:57 UTC, chesterhow commented on src/entity.h
> +	virtual void startDeathAnimation();
Lets stick with either `{}` or `;`

2016-12-02 16:57 UTC, chesterhow commented on src/threechances.cpp
> +				if (player.getDirection() != ATTACK) {
Can we replace the `direction` variable in player class with `action` instead? Like what i've done in the ghost class

2016-12-02 16:57 UTC, chesterhow commented on src/threechances.cpp
> +				GAME_HEIGHT - 120 + 45,
So what is 2, 10 , 45 and 120?

2016-12-02 17:07 UTC, ivantjh commented on src/entity.cpp
>  int currentId = 0;
Its for incrementing the entity id. It cannot be a private variable because once it will always be a new variable with each new entity.

2016-12-02 17:08 UTC, ivantjh commented on src/entity.h
> +	virtual void startDeathAnimation();
missed this

2016-12-02 17:18 UTC, ivantjh commented on src/threechances.cpp
> +				GAME_HEIGHT - 120 + 45,
`/2` to align words in the center of screen. `-10` to remove strange padding on the left of screen when setting word. `45` and `120` is the spacing between words at a scale of `x2`.

2016-12-02 17:18 UTC, ivantjh commented on src/threechances.cpp
> +				GAME_HEIGHT - 120 + 45,
I think we should just change this to image lmao

2016-12-03 01:53 UTC, chesterhow commented on src/threechances.cpp
> +				GAME_HEIGHT - 120 + 45,
Up to you but at least make these numbers constants

2016-12-03 03:55 UTC, chesterhow requested changes

2016-12-03 03:55 UTC, chesterhow commented on src/constants.h
> +const int PLAYER_ATTACK_END_FRAME = 3;
Odd, github says outdated but its still here

2016-12-03 03:55 UTC, chesterhow commented on src/entity.cpp
> +		//this->setAnimating(true);
How come all these commented out?

2016-12-03 03:55 UTC, chesterhow commented on src/player.h
> -	void setDirection(int d) { direction = d; }
Setter and getter for action?

2016-12-03 04:07 UTC, ivantjh commented on src/player.h
> -	void setDirection(int d) { direction = d; }
They are on the `entity` class and player inherits from `entity` class

2016-12-03 04:36 UTC, chesterhow commented on src/player.h
> -	void setDirection(int d) { direction = d; }
Then remove the action variable from player too since its in entity

2016-12-03 04:44 UTC, ivantjh commented on src/entity.cpp
> +		//this->setAnimating(true);
They are pushed to the AI functions to facilitate usage of monsterVec.

2016-12-03 04:48 UTC, ivantjh commented
@chesterhow This branch now fully uses the monsterVec. I am still dealing with an issue of entity death but this pr can be merged into master.

2016-12-03 04:52 UTC, ivantjh commented
Added a hack for now

2016-12-03 15:49 UTC, chesterhow approved these changes

2016-12-03 15:49 UTC, merged