Stage class
CIA-hideout/three-chances pull request #7
Opened 2016-11-23 07:14 UTC by chesterhow

Changes
- Created Stage class to manage 2D array of level

@ivantjh @JxJoker

2016-11-23 12:40 UTC, ivantjh requested changes
Looks okay, not sure if we need setters and getters for each of the private variables in the stage class.

2016-11-23 12:40 UTC, ivantjh commented on src/stage.h
> +
```c++
struct TileCoord {
    int x;
    int y;
}

struct MapCoord {
    float x;
    float y;
}
```

Use this for startTile, endTile, currentTile and all the corresponding methods.

2016-11-23 12:40 UTC, ivantjh commented on src/stage.h
> +
Don't think it is necessary to have a vector only storing two values.

2016-11-23 12:40 UTC, ivantjh commented on src/stage.h
> +	std::vector<int> currentTile;			// Coordinates of current tile
Need to keep `stageNo` variable to know which stage player is on.

2016-11-23 12:40 UTC, ivantjh commented on src/stage.h
> +	int getTileAtCoordinate(std::vector<int> coordinate);
`getTileValueAtMapCoord(MapCoord mc)` to keep it consistent with the bottom method name

2016-11-23 12:40 UTC, ivantjh commented on src/threechances.cpp
> +	std::vector<std::vector<int>> layout = {
Create a new file named 'mapLayout.h' or something relevant and store there. The main game file shouldn't be used to store large data.

2016-11-24 05:16 UTC, chesterhow commented on src/stage.h
> +
Whats the diff between TileCoord and MapCoord?

2016-11-24 06:16 UTC, ivantjh commented on src/stage.h
> +
TileCoord is used to store the indexes of the 2D array. MapCoord is used to store the actual x, y coordinates of the map.

2016-11-24 06:31 UTC, chesterhow commented on src/stage.h
> +
But i only have coordinates. Which is just the indexes. Having 2 will only screw us over

2016-11-24 06:43 UTC, chesterhow commented
@ivantjh @JxJoker made the relevant changes

2016-11-24 06:49 UTC, ivantjh commented on src/stageLayouts.h
> +	Coordinates(int x, int y) : x(x), y(y) {}
Need constructors? Or is that constructor?

2016-11-24 06:50 UTC, ivantjh approved these changes

2016-11-24 06:50 UTC, chesterhow commented on src/stageLayouts.h
> +	Coordinates(int x, int y) : x(x), y(y) {}
Dats right

2016-11-24 06:51 UTC, merged